dnl Process this file with autoconf to produce a configure script.

AC_INIT(configure.in)
AM_INIT_AUTOMAKE(aseqview, 0.3.1)
AC_CONFIG_HEADERS(config.h)

AC_PROG_CC
AC_PROG_INSTALL
AC_HEADER_STDC
AC_C_INLINE

AH_TEMPLATE([HAVE_LIBCAP], [Hey, we have libcap])
AC_CHECK_HEADER(sys/capability.h,
		[AC_CHECK_LIB(cap, cap_get_proc,
			     [AC_DEFINE(HAVE_LIBCAP)
			      LIBS="$LIBS -lcap"])])

AM_PATH_ALSA(0.5.0)
AC_CHECK_HEADERS(alsa/asoundlib.h)

PKG_CHECK_MODULES([GTK], [gtk4],
  [AC_DEFINE([USE_GTK4], [1], [Build with GTK 4])],
  [PKG_CHECK_MODULES([GTK], [gtk+-3.0])])
ASEQVIEW_CFLAGS="$GTK_CFLAGS $ALSA_CFLAGS"
ASEQVIEW_LIBS="$GTK_LIBS $ALSA_LIBS"
AC_SUBST(ASEQVIEW_CFLAGS)
AC_SUBST(ASEQVIEW_LIBS)

AC_OUTPUT(Makefile etc/aseqview.spec)
